In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("Flat.csv")

In [6]:
df

      SIZE
0    2 Bhk
1    3 Bhk
2    4 Bhk
3    5 Bhk
4    6 Bhk
5    7 Bhk
6    8 Bhk
7    9 Bhk
8   10 Bhk
9   11 Bhk
10  12 Bhk
11  13 Bhk
12  14 Bhk
13  15 Bhk

In [10]:
def updateSize(SIZE):
    temp = SIZE.split(" ")
    if( int(temp[0]) > 5):
        return 3
    else:
        return temp[0]

In [12]:
df['newsize'] = df['SIZE'].apply(updateSize)
df

      SIZE newsize
0    2 Bhk       2
1    3 Bhk       3
2    4 Bhk       4
3    5 Bhk       5
4    6 Bhk       3
5    7 Bhk       3
6    8 Bhk       3
7    9 Bhk       3
8   10 Bhk       3
9   11 Bhk       3
10  12 Bhk       3
11  13 Bhk       3
12  14 Bhk       3
13  15 Bhk       3

In [14]:
df.info

<bound method DataFrame.info of       SIZE newsize
0    2 Bhk       2
1    3 Bhk       3
2    4 Bhk       4
3    5 Bhk       5
4    6 Bhk       3
5    7 Bhk       3
6    8 Bhk       3
7    9 Bhk       3
8   10 Bhk       3
9   11 Bhk       3
10  12 Bhk       3
11  13 Bhk       3
12  14 Bhk       3
13  15 Bhk       3>

In [15]:
df = pd.read_csv("Flat.csv")
df

      SIZE        price
0    2 Bhk        34235
1    3 Bhk        64748
2    4 Bhk        85858
3    5 Bhk   4325-43332
4    6 Bhk  33445-54332
5    7 Bhk         2444
6    8 Bhk        42455
7    9 Bhk        45677
8   10 Bhk     466-9987
9   11 Bhk         3356
10  12 Bhk        78699
11  13 Bhk        86979
12  14 Bhk        57776
13  15 Bhk    7888-7774

In [17]:
df.info

<bound method DataFrame.info of       SIZE        price
0    2 Bhk        34235
1    3 Bhk        64748
2    4 Bhk        85858
3    5 Bhk   4325-43332
4    6 Bhk  33445-54332
5    7 Bhk         2444
6    8 Bhk        42455
7    9 Bhk        45677
8   10 Bhk     466-9987
9   11 Bhk         3356
10  12 Bhk        78699
11  13 Bhk        86979
12  14 Bhk        57776
13  15 Bhk    7888-7774>

In [18]:
def updatePrice(price):
    temp = price.split("-")
    if(len(temp) == 2):
        return (float(temp[0]) + float(temp[1]))/2
    else:
        return float(temp[0])

In [19]:
df['price'] = df['price'].apply(updatePrice)
df

      SIZE    price
0    2 Bhk  34235.0
1    3 Bhk  64748.0
2    4 Bhk  85858.0
3    5 Bhk  23828.5
4    6 Bhk  43888.5
5    7 Bhk   2444.0
6    8 Bhk  42455.0
7    9 Bhk  45677.0
8   10 Bhk   5226.5
9   11 Bhk   3356.0
10  12 Bhk  78699.0
11  13 Bhk  86979.0
12  14 Bhk  57776.0
13  15 Bhk   7831.0