In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

## Get the Total Sales of Each product

In [5]:
result = pd.pivot_table(df, index = ['Product'], values = ['Amount'], aggfunc = [np.sum])

In [6]:
result

            sum
         Amount
Product
Banana     1091
Beans       626
Broccoli    301
Carrots     270
Orange      610

## Get the Total Sales of  Each Product

In [7]:
result = pd.pivot_table(df, index = ['Category'], values = ['Amount'], aggfunc = [np.sum])

In [8]:
result

             sum
          Amount
Category
Fruit       1701
Vegetable   1197

## Get the Total Sales by category and Product both

In [9]:
result = pd.pivot_table(df, index = ['Product','Category'], values = ['Amount'], aggfunc = [np.sum])

In [10]:
result

                      sum
                   Amount
Product  Category
Banana   Fruit       1091
Beans    Vegetable    626
Broccoli Vegetable    301
Carrots  Vegetable    270
Orange   Fruit        610

## Get the Mean, Median, Minimum Sale by Category

In [11]:
result = pd.pivot_table(df, index = ['Category'], values = ['Amount'], aggfunc = [np.mean, np.median, np.min])

In [12]:
result

             mean median    min
           Amount Amount Amount
Category
Fruit      425.25  497.0     90
Vegetable  299.25  254.5     62