In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("SaleData.csv")
df

,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1-6-18,East,Martha,Alexander,Television,95.0,"1,198.00","1,13,810.00"
1,1-23-18,Central,Hermann,Shelli,Home Theater,50.0,500.00,"25,000.00"
2,2-9-18,Central,Hermann,Luis,Television,36.0,"1,198.00","43,128.00"
3,2-26-18,Central,Timothy,David,Cell Phone,27.0,225.00,"6,075.00"
4,3-15-18,West,Timothy,Stephen,Television,56.0,"1,198.00","67,088.00"
5,4-1-18,East,Martha,Alexander,Home Theater,60.0,500.00,"30,000.00"
6,4-18-18,Central,Martha,Steven,Television,75.0,"1,198.00","89,850.00"
7,5-5-18,Central,Hermann,Luis,Television,90.0,"1,198.00","1,07,820.00"
8,5-22-18,West,Douglas,Michael,Television,32.0,"1,198.00","38,336.00"
9,6-8-18,East,Martha,Alexander,Home Theater,60.0,500.00,"30,000.00"
10,6-25-18,Central,Hermann,Sigal,Television,90.0,"1,198.00","1,07,820.00"
11,7-12-18,East,Martha,Diana,Home Theater,29.0,500.00,"14,500.00"
12,7-29-18,East,Douglas,Karen,Home Theater,81.0,500.00,"40,500.00"
13,8-15-18,East,Martha,Alexander,Television,35.0,"1,198.00","41,930.00"
14,9-1-18,Central,Douglas,John,Desk,2.0,125.00,250.00
15,9-18-18,East,Martha,Alexander,Video Games,16.0,58.50,936.00
16,10-5-18,Central,Hermann,Sigal,Home Theater,28.0,500.00,"14,000.00"
17,10-22-18,East,Martha,Alexander,Cell Phone,64.0,225.00,"14,400.00"
18,11-8-18,East,Douglas,Karen,Cell Phone,15.0,225.00,"3,375.00"
19,11-25-18,Central,Hermann,Shelli,Video Games,96.0,58.50,"5,616.00"
20,12-12-18,Central,Douglas,John,Television,67.0,"1,198.00","80,266.00"
21,12-29-18,East,Douglas,Karen,Video Games,74.0,58.50,"4,329.00"
22,1-15-19,Central,Timothy,David,Home Theater,46.0,500.00,"23,000.00"
23,2-1-19,Central,Douglas,John,Home Theater,87.0,500.00,"43,500.00"
24,2-18-19,East,Martha,Alexander,Home Theater,4.0,500.00,"2,000.00"
25,3-7-19,West,Timothy,Stephen,Home Theater,7.0,500.00,"3,500.00"
26,3-24-19,Central,Hermann,Luis,Video Games,50.0,58.50,"2,925.00"
27,4-10-19,Central,Martha,Steven,Television,66.0,"1,198.00","79,068.00"
28,4-27-19,East,Martha,Diana,Cell Phone,96.0,225.00,"21,600.00"
29,5-14-19,Central,Timothy,David,Television,53.0,"1,198.00","63,494.00"
30,5-31-19,Central,Timothy,David,Home Theater,80.0,500.00,"40,000.00"
31,6-17-19,Central,Hermann,Shelli,Desk,5.0,125.00,625.00
32,7-4-19,East,Martha,Alexander,Video Games,62.0,58.50,"3,627.00"
33,7-21-19,Central,Hermann,Sigal,Video Games,55.0,58.50,"3,217.50"
34,8-7-19,Central,Hermann,Shelli,Video Games,42.0,58.50,"2,457.00"
35,8-24-19,West,Timothy,Stephen,Desk,3.0,125.00,375.00
36,9-10-19,Central,Timothy,David,Television,7.0,"1,198.00","8,386.00"
37,9-27-19,West,Timothy,Stephen,Cell Phone,76.0,225.00,"17,100.00"
38,10-14-19,West,Douglas,Michael,Home Theater,57.0,500.00,"28,500.00"
39,10-31-19,Central,Martha,Steven,Television,14.0,"1,198.00","16,772.00"
40,11-17-19,Central,Hermann,Luis,Home Theater,11.0,500.00,"5,500.00"
41,12-4-19,Central,Hermann,Luis,Home Theater,94.0,500.00,"47,000.00"
42,12-21-19,Central,Martha,Steven,Home Theater,28.0,500.00,"14,000.00"
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Write a Pandas Program to create a pivot table and find the item wise unit sold

In [7]:
result = pd.pivot_table(df, index = ['Region','Manager'], values = ['Sale_amt'], aggfunc = [np.sum])
result

                                                               sum
                                                          Sale_amt
Region  Manager
Central Douglas                      250.00  80,266.00  43,500.00
        Hermann   25,000.00  43,128.00  1,07,820.00  1,07,820.0...
        Martha         89,850.00  79,068.00  16,772.00  14,000.00
        Timothy   6,075.00  23,000.00  63,494.00  40,000.00  8,...
East    Douglas                     40,500.00  3,375.00  4,329.00
        Martha    1,13,810.00  30,000.00  30,000.00  14,500.00 ...
West    Douglas                              38,336.00  28,500.00
        Timothy            67,088.00  3,500.00  375.00  17,100.00

## Write a Pandas Program to create a pivot table and find the region wise total sale

In [8]:
result = pd.pivot_table(df, index = ['Region'], values = ['Sale_amt'], aggfunc = [np.sum])
result

                                                       sum
                                                  Sale_amt
Region
Central   25,000.00  43,128.00  6,075.00  89,850.00  1,...
East      1,13,810.00  30,000.00  30,000.00  14,500.00 ...
West      67,088.00  38,336.00  3,500.00  375.00  17,10...

## Write a Pandas Program to create a pivot table and count the manager wise sale and mean value of sale amount

## Write a Pandas Program to create a pivot table and find wise manager wise, salesman wise total sale and also display the sum of all sale amount at the bottom

In [16]:
table = pd.pivot_table(df, index =["Manager","SalesMan"],values =["Units",'Sale_amt'],
                       aggfunc=[np.sum],fill_value=0,margins=True)
table

TypeError: Invalid value ' 1,13,810.00  25,000.00  43,128.00  6,075.00  67,088.00  30,000.00  89,850.00  1,07,820.00  38,336.00  30,000.00  1,07,820.00  14,500.00  40,500.00  41,930.00  250.00  936.00  14,000.00  14,400.00  3,375.00  5,616.00  80,266.00  4,329.00  23,000.00  43,500.00  2,000.00  3,500.00  2,925.00  79,068.00  21,600.00  63,494.00  40,000.00  625.00  3,627.00  3,217.50  2,457.00  375.00  8,386.00  17,100.00  28,500.00  16,772.00  5,500.00  47,000.00  14,000.00 ' for dtype 'float64'

In [17]:
df["Sale_amt"] = pd.to_numeric(
    df["Sale_amt"].str.replace(",", "", regex=False)
)

In [18]:
table = pd.pivot_table(
    df,
    index=["Manager", "SalesMan"],
    values=["Units", "Sale_amt"],
    aggfunc=np.sum,
    fill_value=0,
    margins=True
)

print(table)

                    Sale_amt   Units
Manager SalesMan
Douglas John        124016.0   156.0
        Karen        48204.0   170.0
        Michael      66836.0    89.0
Hermann Luis        206373.0   281.0
        Shelli       33698.0   193.0
        Sigal       125037.5   173.0
Martha  Alexander   236703.0   396.0
        Diana        36100.0   125.0
        Steven      199690.0   183.0
Timothy David       140955.0   213.0
        Stephen      88063.0   142.0
All                1305675.5  2121.0

## Write a Pandas Program to create a pivot table and find the total sale amount region wise, manager wise, salesman wise where Manager = "Doughals"

In [19]:
import pandas as pd
import numpy as np

# Convert Sale_amt to numeric (if it contains commas)
df["Sale_amt"] = (
    df["Sale_amt"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)

# Filter data for Manager = "Doughals"
df1 = df[df["Manager"] == "Doughals"]

# Create Pivot Table
table = pd.pivot_table(
    df1,
    index=["Region", "Manager", "SalesMan"],
    values="Sale_amt",
    aggfunc=np.sum,
    fill_value=0,
    margins=True
)

print(table)

                         Sale_amt
Region Manager SalesMan
All                           0.0

In [24]:
table = pd.pivot_table(
    df[df["Manager"] == "Doughals"],
    index=["Region", "Manager", "SalesMan"],
    values="Sale_amt",
    aggfunc="sum",
)

table

Empty DataFrame
Columns: []
Index: []

In [26]:
table = pd.pivot_table(
    df[df["Manager"] == "Douglas"],
    index=["Region", "Manager", "SalesMan"],
    values="Sale_amt",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

print(table)

                          Sale_amt
Region  Manager SalesMan
Central Douglas John      124016.0
East    Douglas Karen      48204.0
West    Douglas Michael    66836.0
All                       239056.0

## Write a Pandas Program to create a pivot table and find the region wise television and home theater sold

In [27]:
df1 = df[df["Item"].isin(["Television", "Home Theater"])]

In [28]:
table = pd.pivot_table(
    df1,
    index="Region",
    columns="Item",
    values="Units",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

print(table)

Item     Home Theater  Television     All
Region
Central         424.0       498.0   922.0
East            234.0       130.0   364.0
West             64.0        88.0   152.0
All             722.0       716.0  1438.0