In [1]:
import pandas as pd
import  numpy  as  np

In [2]:
student = pd.read_csv("Student.csv")
student

   RollNo      Name depid
0     101      abhi  D001
1     102       raj  D001
2     103     kumar  D002
3     104  abhiskek  D001
4     105   fardeen  D003
5     106   yougesh  D001
6     107    ganesh  D002
7     108    goyrav  D003
8     109    rajesh  D001
9     110      raju  D003

In [3]:
department = pd.read_csv("department .csv")
department

  depid dname       HodName
0  D001   CSE       LUV Sir
1  D002   ITE    Vishal Sir
2  D003   MCA  Pradhasn Sir

In [6]:
merged_data = pd.merge(student, department,  on ='depid')
merged_data

   RollNo      Name depid dname       HodName
0     101      abhi  D001   CSE       LUV Sir
1     102       raj  D001   CSE       LUV Sir
2     103     kumar  D002   ITE    Vishal Sir
3     104  abhiskek  D001   CSE       LUV Sir
4     105   fardeen  D003   MCA  Pradhasn Sir
5     106   yougesh  D001   CSE       LUV Sir
6     107    ganesh  D002   ITE    Vishal Sir
7     108    goyrav  D003   MCA  Pradhasn Sir
8     109    rajesh  D001   CSE       LUV Sir
9     110      raju  D003   MCA  Pradhasn Sir

In [7]:
data =merged_data.loc[(merged_data['RollNo'] ==  101)  | (merged_data['RollNo'] ==  102)] 
data

   RollNo  Name depid dname  HodName
0     101  abhi  D001   CSE  LUV Sir
1     102   raj  D001   CSE  LUV Sir

## print the no of student department wisem

In [8]:
result = merged_data.groupby('dname')['RollNo'].count()
result

dname
CSE    5
ITE    2
MCA    3
Name: RollNo, dtype: int64

In [9]:
merged_new = pd.merge(student, department,  left_on ='depid', right_on='department')
merged_new

KeyError: 'department'

In [12]:
student_df = pd.read_csv("Student.csv")
student_df

   RollNo      Name depid
0     101      abhi  D001
1     102       raj  D001
2     103     kumar  D002
3     104  abhiskek  D001
4     105   fardeen  D003
5     106   yougesh  D001
6     107    ganesh  D002
7     108    goyrav  D003
8     109    rajesh  D001
9     110      raju  D003

In [13]:
department_df = pd.read_csv("Student.csv")
department_df

   RollNo      Name depid
0     101      abhi  D001
1     102       raj  D001
2     103     kumar  D002
3     104  abhiskek  D001
4     105   fardeen  D003
5     106   yougesh  D001
6     107    ganesh  D002
7     108    goyrav  D003
8     109    rajesh  D001
9     110      raju  D003

In [14]:
merge_df = pd.merge(student_df,department_df,left_on ='department',right_on='depid')

KeyError: 'department'