In [1]:
import pandas as pd
import numpy as np

Write a Pandas program to merge two DataFrames on a single column.

DataFrames on a single column.

In [5]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})
df1

   ID     Name
0   1   Selena
1   2  Annabel
2   3    Caeso

In [7]:
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Age': [25, 30, 22]
})
df2

   ID  Age
0   2   25
1   3   30
2   4   22

In [11]:
merged_data = pd.merge(df1, df2,  on ='ID')
merged_data

   ID     Name  Age
0   2  Annabel   25
1   3    Caeso   30

 Write a Pandas program to merge two DataFrames on a single column ensuring that duplicate entries in the left DataFrame are preserved.

In [8]:
df_left = pd.DataFrame({
    'student_id': [101, 102, 102, 103],  # 102 is duplicated
    'course': ['Math', 'Science', 'History', 'Art']
})
df_left

   student_id   course
0         101     Math
1         102  Science
2         102  History
3         103      Art

In [10]:
df_right = pd.DataFrame({
    'student_id': [101, 102, 103, 104],
    'student_name': ['Alice', 'Bob', 'Charlie', 'David']})
df_right

   student_id student_name
0         101        Alice
1         102          Bob
2         103      Charlie
3         104        David

 Write a Pandas program to merge two DataFrames on a single column with case‐insensitive matching on string keys

In [12]:
df1 = pd.DataFrame({
    'Key': ['Apple', 'Banana', 'CHERRY'],
    'Stock': [100, 200, 300]
})
df1

      Key  Stock
0   Apple    100
1  Banana    200
2  CHERRY    300

In [13]:
df2 = pd.DataFrame({
    'Key': ['Apple', 'BANANA', 'cherry'],
    'Price': [1.2, 0.5, 2.5]
})
df2

      Key  Price
0   Apple    1.2
1  BANANA    0.5
2  cherry    2.5

In [15]:
merged_data1 = pd.merge(df1, df2,  on ='Key')
merged_data1

     Key  Stock  Price
0  Apple    100    1.2

In [16]:
df1 = pd.DataFrame(
    {"id": [1, 2, np.nan, 4], "val1": ["Alpha", "Beta", "Gamma", "Delta"]}
)

In [17]:
df2 = pd.DataFrame({"id": [1, 2, 3, np.nan], "val2": [10, 20, 30, 40]})

In [18]:
merge_data1=pd.merge(df1,df2,on='id').dropna(subset=["id"])

In [19]:
merge_data1

    id   val1  val2
0  1.0  Alpha    10
1  2.0   Beta    20

In [20]:
df_left = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'value_left': [10, 20, 30, 40, 100]  # Median is 30.0
})

In [23]:
merged_df=pd.merge(df_left,df_right,on ='id',how='left')
merged_df

   id  value_left  value_right
0   1          10        150.0
1   2          20        250.0
2   3          30        350.0
3   4          40          NaN
4   5         100          NaN

In [29]:
merged_df['value_right']=merge_df['value_right'].fillna(left_median)
merged_df

NameError: name 'left_median' is not defined

In [21]:
df_right = pd.DataFrame({
    'id': [1, 2, 3],
    'value_right': [150, 250, 350]
})

In [22]:
merge_df=pd.merge(df_left,df_right,on='id')
merge_df

   id  value_left  value_right
0   1          10          150
1   2          20          250
2   3          30          350

In [30]:
df_left = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

In [33]:

df_right = pd.DataFrame({
    'Emp_ID': [101, 102, 105],
    'Dept': ['HR', 'IT', 'Finance']
})

In [34]:
df_left

   Emp_ID     Name
0     101    Alice
1     102      Bob
2     103  Charlie
3     104    David

In [35]:
df_right

   Emp_ID     Dept
0     101       HR
1     102       IT
2     105  Finance

In [36]:
join_df=pd.merge(df_left,df_right,on='Emp_ID')
join_df

   Emp_ID   Name Dept
0     101  Alice   HR
1     102    Bob   IT

In [38]:
left_row_preserved =pd.left["Emp_ID"].isin(join_df['Emp_ID']).all()
left_row_preserved

AttributeError: module 'pandas' has no attribute 'left'

In [39]:
df_left = pd.DataFrame({
    'user_id': [101, 102, 103, 104],
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})
df_left

   user_id     name
0      101    Alice
1      102      Bob
2      103  Charlie
3      104    David

In [40]:
df_right = pd.DataFrame({
    'user_id': [101, 102, 103],
    'signup_score': [85, 95, 70]  # Column from the right DataFrame
})
df_right

   user_id  signup_score
0      101            85
1      102            95
2      103            70

In [42]:
merge_df=pd.merge(df_left,df_right,on="user_id")
merged_df

   id  value_left  value_right
0   1          10        150.0
1   2          20        250.0
2   3          30        350.0
3   4          40          NaN
4   5         100          NaN

In [44]:
sorted_df = merged_df.sort_values (by='signup_score', ascending=True)
sorted_df

KeyError: 'signup_score'

In [45]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso'],
    'Age': [25, 30, 22]
})
df1

   ID     Name  Age
0   1   Selena   25
1   2  Annabel   30
2   3    Caeso   22

In [46]:
df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso'],
    'Salary': [50000, 60000, 70000]
})
df2

   ID     Name  Salary
0   1   Selena   50000
1   2  Annabel   60000
2   3    Caeso   70000

In [47]:
merged_df=pd.merge(df1,df2,on=['ID','Name'])
merged_df

   ID     Name  Age  Salary
0   1   Selena   25   50000
1   2  Annabel   30   60000
2   3    Caeso   22   70000

In [48]:

df_left = pd.DataFrame({
    'emp_id': [101, 102, 103],
    'name': ['Alice', 'Bob', 'Charlie']
})
df_left

   emp_id     name
0     101    Alice
1     102      Bob
2     103  Charlie

In [51]:
df_right = pd.DataFrame({
    'employee_number': [101, 102, 103],
    'department': ['HR', 'IT', 'Finance']
})
df_right

   employee_number department
0              101         HR
1              102         IT
2              103    Finance

In [53]:
merged_df=pd.merge(df1,df2,left_on='emp_id',right_on='employee_number').drop(columns='employee_number')
merged_df

KeyError: 'employee_number'