In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("libdata.csv")
df

   Rollno BookId          DOI         DOR  Fine
0     101    B001  12-07-2025  15-07-2025    50
1     102    B002  18-07-2025  20-07-2025    63
2     103    B001  24-07-2025  25-07-2025    42
3     104    B003  30-07-2025  30-07-2025     0

In [3]:
df1 = pd.read_csv("student1.csv")
df1

   Rollno     Name department
0     101  fardeen        mca
1     102   ganesh        ite
2     103  yougesh        cse

In [4]:
merged_data = pd.merge(df, df1,  on ='Rollno')
merged_data

   Rollno BookId          DOI         DOR  Fine     Name department
0     101    B001  12-07-2025  15-07-2025    50  fardeen        mca
1     102    B002  18-07-2025  20-07-2025    63   ganesh        ite
2     103    B001  24-07-2025  25-07-2025    42  yougesh        cse

In [5]:
merged_data.describe

<bound method NDFrame.describe of    Rollno BookId          DOI         DOR  Fine     Name department
0     101    B001  12-07-2025  15-07-2025    50  fardeen        mca
1     102    B002  18-07-2025  20-07-2025    63   ganesh        ite
2     103    B001  24-07-2025  25-07-2025    42  yougesh        cse>