In [100]:
import pandas as pd
import numpy as np

In [101]:
df = pd.read_csv("placement.csv")
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [102]:
X = df.iloc[:,0:1]
X

     cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [103]:
y = df.iloc[:,-1]
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ...
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2)

In [106]:
X_train

     cgpa
30   7.36
84   4.26
34   7.34
127  6.78
175  7.04
..    ...
72   7.78
144  6.17
11   6.61
76   6.94
97   5.98

[160 rows x 1 columns]

In [107]:
X_test

     cgpa
63   9.16
186  7.84
130  6.68
181  8.22
194  7.89
120  5.23
15   7.25
113  6.94
77   8.99
199  6.22
43   7.66
116  9.04
155  6.98
129  7.29
166  8.60
45   7.87
28   5.94
177  7.09
150  6.30
35   6.87
149  8.28
1    5.12
170  6.22
57   6.60
5    7.89
161  7.30
55   8.20
192  8.25
154  7.08
93   6.79
173  6.75
33   6.35
189  8.11
98   7.69
52   8.37
180  6.19
90   7.11
53   6.47
128  7.93
178  8.15

In [108]:
X_test.shape

(40, 1)

In [109]:
from sklearn.linear_model import LinearRegression

In [110]:
lr = LinearRegression()

In [111]:
lr.fit(X_train, y_train)

LinearRegression()

In [112]:
y_pred = lr.predict(X_test)
y_pred

array([4.24171141, 3.4911422 , 2.83155107, 3.70721515, 3.51957285,
       2.00706217, 3.1556605 , 2.97939046, 4.14504719, 2.56998907,
       3.38879185, 4.17347784, 3.00213498, 3.17840503, 3.92328811,
       3.50820059, 2.41077742, 3.06468242, 2.61547812, 2.93958755,
       3.74133193, 1.94451473, 2.56998907, 2.78606203, 3.51957285,
       3.18409116, 3.69584289, 3.72427354, 3.05899629, 2.89409851,
       2.87135398, 2.64390877, 3.64466772, 3.40585024, 3.79250711,
       2.55293068, 3.07605468, 2.71214233, 3.54231737, 3.66741224])

In [113]:
y_test

63     4.25
186    3.47
130    2.49
181    3.89
194    3.67
120    1.73
15     3.23
113    2.37
77     4.60
199    2.33
43     2.76
116    3.33
155    3.09
129    3.12
166    3.98
45     3.58
28     2.24
177    3.64
150    2.73
35     2.87
149    3.67
1      1.98
170    2.87
57     1.94
5      2.99
161    3.33
55     3.39
192    3.75
154    2.85
93     3.08
173    2.56
33     2.73
189    4.06
98     3.83
52     4.11
180    2.72
90     2.66
53     2.61
128    3.34
178    3.63
Name: package, dtype: float64

In [114]:
y_test_arr = y_test.to_numpy()
y_test_arr

array([4.25, 3.47, 2.49, 3.89, 3.67, 1.73, 3.23, 2.37, 4.6 , 2.33, 2.76,
       3.33, 3.09, 3.12, 3.98, 3.58, 2.24, 3.64, 2.73, 2.87, 3.67, 1.98,
       2.87, 1.94, 2.99, 3.33, 3.39, 3.75, 2.85, 3.08, 2.56, 2.73, 4.06,
       3.83, 4.11, 2.72, 2.66, 2.61, 3.34, 3.63])

In [115]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [116]:
mae = mean_absolute_error(y_test, y_pred)

In [117]:
print(mae)

0.2542859603161277

## We are goint to write  our own MAE

In [118]:
sum = 0; 
for i in range(len(y_pred)):
    print(y_pred[i])
    print(y_test_arr[i])
    sum = sum + abs(y_test_arr[i] - y_pred[i])
    print("...........")
    my_mae = sum / len(y_pred)
    print(my_mae)

4.241711408231094
4.25
...........
0.00020721479422265433
3.4911421970038607
3.47
...........
0.0007357697193191681
2.8315510719859893
2.49
...........
0.009274546518968895
3.7072151517510954
3.89
...........
0.013844167725191514
3.519572848944286
3.67
...........
0.017604846501584358
2.0070621657136503
1.73
...........
0.024531400644425615
3.1556605041068404
3.23
...........
0.026389888041754607
2.979390462076202
2.37
...........
0.041624649593659656
4.1450471916336475
4.6
...........
0.05299846980281846
2.5699890741340745
2.33
...........
0.05899819665617032
3.3887918500183294
2.76
...........
0.07471799290662856
4.173477843574073
3.33
...........
0.09580493899598039
3.002134983628543
3.09
...........
0.0980015644052668
3.1784050256591807
3.12
...........
0.09946169004674632
3.9232881064983283
3.98
...........
0.10087948738428812
3.508200588168117
3.58
...........
0.10267447268008519
2.4107774232676924
2.24
...........
0.10694390826177749
3.0646824178974783
3.64
...........
0.12132684781434053
2.6154781172387556
2.73
...........
0.12418989488337165
2.9395875493596066
2.87
...........
0.1259295836173618
3.741331934079605
3.67
...........
0.12771288196935196
1.944514731444714
1.98
...........
0.1286000136832341
2.5699890741340745
2.87
...........
0.13610028682988223
2.7860620288813083
1.94
...........
0.15725183755191496
3.519572848944286
2.99
...........
0.1704911587755221
3.184091156047266
3.33
...........
0.17413887987434046
3.6958428909749244
3.39
...........
0.18178495214871354
3.7242735429153506
3.75
...........
0.1824281135758298
3.0589962875093932
2.85
...........
0.18765302076356463
2.8940985062549256
3.08
...........
0.1923005581071915
2.8713539847025853
2.56
...........
0.2000844077247561
2.643908769179181
2.73
...........
0.2022366884952766
3.6446677174821587
4.06
...........
0.21261999555822264
3.4058502411825846
3.83
...........
0.22322373952865804
3.7925071075723715
4.11
...........
0.23116106183934876
2.5529306829698197
2.72
...........
0.23533779476510325
3.0760546786736493
2.66
...........
0.2457391617319445
2.7121423338362023
2.61
...........
0.24829272007784953
3.5423173704966273
3.34
...........
0.2533506543402652
3.6674122390345
3.63
...........
0.2542859603161277

In [119]:
mse = mean_squared_error(y_test, y_pred)

In [120]:
print(mse)

0.1123393567862609

In [124]:
def my_mean_squared_error (x_pred, y_pred) :
    sum = 0;
    for i in range(len(x_pred)):
        sum = sum + (x_pred[i] - y_pred[i]) * (x_pred[i] - y_pred[i])
        result = sum / len(y_pred)
        return result

In [125]:
mse1 = my_mean_squared_error(y_test_arr, y_pred)

In [126]:
mse1

np.float64(1.7175188377894789e-06)

In [127]:
result_r2_score = r2_score(y_test, y_pred)
result_r2_score

0.7478760502365325

## Now we are going to calculate our own R2_Square

In [129]:
sum_numerator = 0
sum_denominator = 0
for i in range(40):
    sum_numerator = sum_numerator + (y_test_arr[i] - y_pred[i]) * (y_test_arr[i] - y_pred[i])
    sum_denominator = sum_denominator + (y_test_arr[i] - np.mean(y_test_arr)) * (y_test_arr[i] - np.mean(y_test_arr))
print(sum_numerator)
print(sum_denominator)

4.493574271450438
17.822877499999997

In [130]:
r_score_result = (1-(sum_numerator) / (sum_denominator))
r_score_result

np.float64(0.7478760502365323)