In [1]:
import pandas as pd
import numpy as np

In [3]:
## pandas

In [4]:
df = pd.DataFrame()
columns:[]
Indx:[]

In [5]:
print(type(df))

<class 'pandas.DataFrame'>

In [6]:
## data frame from list

In [7]:
data = ['ram','shyam', 'Mohan', 'Sohan']
df = pd.DataFrame(data)
print(df)

       0
0    ram
1  shyam
2  Mohan
3  Sohan

In [9]:
df[0]

0      ram
1    shyam
2    Mohan
3    Sohan
Name: 0, dtype: str

In [11]:
## Making Data Frame From List to List 1

In [12]:
data = [['Ram', 23, 89000], ['Shyam', 22, 23000], ['Mohan', 24, 7800]]
df = pd.DataFrame(data)

In [13]:
print(df)

       0   1      2
0    Ram  23  89000
1  Shyam  22  23000
2  Mohan  24   7800

In [15]:
df[1]

0    23
1    22
2    24
Name: 1, dtype: int64

In [21]:
df.rename(columns={0: 'Name', 1: 'Age', 2: 'Salary'}, inplace = True)

In [22]:
df['Name']

0      Ram
1    Shyam
2    Mohan
Name: Name, dtype: str

In [23]:
df

    Name  Age  Salary
0    Ram   23   89000
1  Shyam   22   23000
2  Mohan   24    7800

In [25]:
## To Print the content of row 1

In [26]:
df.loc[0]

Name        Ram
Age          23
Salary    89000
Name: 0, dtype: object

In [27]:
df.iloc[0]

Name        Ram
Age          23
Salary    89000
Name: 0, dtype: object

In [31]:
df.loc[[0, 1]]

    Name  Age  Salary
0    Ram   23   89000
1  Shyam   22   23000

In [2]:
df = pd.read_csv("sample.csv")
df

NameError: name 'pd' is not defined