In [1]:
import pandas as pd
import numpy as np

In [6]:
exam_data = {
    'name': ['Sushant', 'Divya', 'Ajay', 'Rohan', 'Fardeen', 'Sakshi', 'Gourav', 'Tanisha', 'Tanu', 'Amit'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1,3,2,3,2,3,1,1,2,1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes',],
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
df

      name  score  attempts qualify
a  Sushant   12.5         1     yes
b    Divya    9.0         3      no
c     Ajay   16.5         2     yes
d    Rohan    NaN         3      no
e  Fardeen    9.0         2      no
f   Sakshi   20.0         3     yes
g   Gourav   14.5         1     yes
h  Tanisha    NaN         1      no
i     Tanu    8.0         2      no
j     Amit   19.0         1     yes

## Select 'name' and 'score' columns in row 1,3,5,6 from the following data

In [10]:
data = df.iloc[[1,3,5,6], [0,1]]
data

     name  score
b   Divya    9.0
d   Rohan    NaN
f  Sakshi   20.0
g  Gourav   14.5

In [12]:
## Write a program to select row  attempts > 2

In [15]:
filtered_data = df[df['attempts']>2]
filtered_data

     name  score  attempts qualify
b   Divya    9.0         3      no
d   Rohan    NaN         3      no
f  Sakshi   20.0         3     yes

In [16]:
filtered_data = df.loc[(df['attempts']>2)]
filtered_data

     name  score  attempts qualify
b   Divya    9.0         3      no
d   Rohan    NaN         3      no
f  Sakshi   20.0         3     yes

In [17]:
filtered_data = df.query('attempts>2')
filtered_data

     name  score  attempts qualify
b   Divya    9.0         3      no
d   Rohan    NaN         3      no
f  Sakshi   20.0         3     yes

In [20]:
filtered_data = df.loc[(df['attempts']>2) & (df['qualify'] == 'yes')]
filtered_data

     name  score  attempts qualify
f  Sakshi   20.0         3     yes

In [21]:
filtered_data = df.query("attempts > 2 & qualify == 'yes'")
filtered_data

     name  score  attempts qualify
f  Sakshi   20.0         3     yes

## Write a pandas program to count the number of rows and columns of DataFrame

In [23]:
no_of_rows = len(df.axes[0])
no_of_coloumns = len(df.axes[1])

In [24]:
print(no_of_rows)

10

In [26]:
print(no_of_coloumns)

4

In [39]:
filtered_data = df.query("score > 15 | score > 20")
filtered_data

     name  score  attempts qualify
c    Ajay   16.5         2     yes
f  Sakshi   20.0         3     yes
j    Amit   19.0         1     yes

In [31]:
## d row ko print karna hai

In [32]:
df

      name  score  attempts qualify
a  Sushant   12.5         1     yes
b    Divya    9.0         3      no
c     Ajay   16.5         2     yes
d    Rohan    NaN         3      no
e  Fardeen    9.0         2      no
f   Sakshi   20.0         3     yes
g   Gourav   14.5         1     yes
h  Tanisha    NaN         1      no
i     Tanu    8.0         2      no
j     Amit   19.0         1     yes

In [33]:
df.loc['d','score']

np.float64(nan)

In [34]:
df.loc['d','score'] = 11.5

In [35]:
df

      name  score  attempts qualify
a  Sushant   12.5         1     yes
b    Divya    9.0         3      no
c     Ajay   16.5         2     yes
d    Rohan   11.5         3      no
e  Fardeen    9.0         2      no
f   Sakshi   20.0         3     yes
g   Gourav   14.5         1     yes
h  Tanisha    NaN         1      no
i     Tanu    8.0         2      no
j     Amit   19.0         1     yes

## Write a pandas program to replace the qualify collumn contains the value 'Yes' and 'No' with True and False

In [41]:
df['qualify'] = df['qualify'].map({'yes': True, 'no': False})
df

      name  score  attempts  qualify
a  Sushant   12.5         1     True
b    Divya    9.0         3    False
c     Ajay   16.5         2     True
d    Rohan   11.5         3    False
e  Fardeen    9.0         2    False
f   Sakshi   20.0         3     True
g   Gourav   14.5         1     True
h  Tanisha    NaN         1    False
i     Tanu    8.0         2    False
j     Amit   19.0         1     True

In [53]:
df['remark'] = df['qualify'].map({True: 'Congrasulations', False: 'Try Again'})
df

      name  score  attempts  qualify           remark
a  Sushant   12.5         1     True  Congrasulations
b    Divya    9.0         3    False        Try Again
c     Ajay   16.5         2     True  Congrasulations
d    Rohan   11.5         3    False        Try Again
e  Fardeen    9.0         2    False        Try Again
f   Sakshi   20.0         3     True  Congrasulations
g   Gourav   14.5         1     True  Congrasulations
h  Tanisha    NaN         1    False        Try Again
i     Tanu    8.0         2    False        Try Again
j     Amit   19.0         1     True  Congrasulations