In [1]:
import pandas as pd
import numpy as np

In [2]:
## make a csv file of following data
## rollno, name, branch, book_title, issuDate, returndate, fine
## make 15 entries
## 1) no of books issued by each studennt
## 2) total fine paid by each student 
## 3) how many times student issused the same book
## 4) calculate the avg, max, min fine paid by each student
## 5) Total fine paid by branch wise
## 6) No of book issued date wise

In [34]:
df = pd.DataFrame({
    'rollno': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
    'name': [
        'Aarav Sharma', 'Priya Singh', 'Rohan Verma', 'Anjali Mishra', 'Vikas Yadav',
        'Anjali Mishra', 'Ritika Jain', 'Simran Kaur', 'Raj Malhotra', 'Pooja Sharma',
        'Aditya Kumar', 'Simran Kaur', 'Sachin Chauhan', 'Ritika Jain', 'Sachin Chauhan'
    ],
    'branch': [
        'CSE', 'IT', 'ECE', 'CSE', 'Civil',
        'CSE', 'IT', 'ECE', 'ME', 'Civil',
        'CSE', 'IT', 'ECE', 'ME', 'CSE'
    ],
    'book_title': [
        'Data Structures', 'Python Programming', 'Digital Electronics',
        'Database Systems', 'Data Structures', 'Database Systems',
        'Machine Learning', 'Microprocessors', 'Thermodynamics',
        'Database Systems', 'Operating Systems', 'Operating Systems',
        'Surveying Basics', 'Operating Systems', 'Computer Networks'
    ],
    'issueDate': [
        '01/June/2026', '03/June/2026', '05/June/2026', '09/June/2026', '08/June/2026',
        '09/June/2026', '10/June/2026', '11/June/2026', '15/June/2026', '13/June/2026',
        '14/June/2026', '15/June/2026', '16/June/2026', '10/June/2026', '18/June/2026'
    ],
    'returnDate': [
        '15/June/2026', '17/June/2026', '01/July/2026', '20/June/2026', '22/June/2026',
        '23/June/2026', '26/June/2026', '25/June/2026', '26/June/2026', '27/June/2026',
        '28/June/2026', '29/June/2026', '30/June/2026', '01/July/2026', '02/July/2026'
    ],
    'fine': [0, 10, 0, 20, 0, 15, 0, 5, 0, 25, 0, 10, 0, 30, 0]
})
df

,rollno,name,branch,book_title,issueDate,returnDate,fine
0,101,Aarav Sharma,CSE,Data Structures,01/June/2026,15/June/2026,0
1,102,Priya Singh,IT,Python Programming,03/June/2026,17/June/2026,10
2,103,Rohan Verma,ECE,Digital Electronics,05/June/2026,01/July/2026,0
3,104,Anjali Mishra,CSE,Database Systems,09/June/2026,20/June/2026,20
4,105,Vikas Yadav,Civil,Data Structures,08/June/2026,22/June/2026,0
5,106,Anjali Mishra,CSE,Database Systems,09/June/2026,23/June/2026,15
6,107,Ritika Jain,IT,Machine Learning,10/June/2026,26/June/2026,0
7,108,Simran Kaur,ECE,Microprocessors,11/June/2026,25/June/2026,5
8,109,Raj Malhotra,ME,Thermodynamics,15/June/2026,26/June/2026,0
9,110,Pooja Sharma,Civil,Database Systems,13/June/2026,27/June/2026,25
10,111,Aditya Kumar,CSE,Operating Systems,14/June/2026,28/June/2026,0
11,112,Simran Kaur,IT,Operating Systems,15/June/2026,29/June/2026,10
12,113,Sachin Chauhan,ECE,Surveying Basics,16/June/2026,30/June/2026,0
13,114,Ritika Jain,ME,Operating Systems,10/June/2026,01/July/2026,30
14,115,Sachin Chauhan,CSE,Computer Networks,18/June/2026,02/July/2026,0

In [6]:
result = df.groupby('name').size()
result

name
Aarav Sharma      1
Aditya Kumar      1
Anjali Mishra     2
Pooja Sharma      1
Priya Singh       1
Raj Malhotra      1
Ritika Jain       2
Rohan Verma       1
Sachin Chauhan    2
Simran Kaur       2
Vikas Yadav       1
dtype: int64

## No of books issued by each student

In [12]:
result = df.groupby('book_title').sum()
result

,rollno,name,branch,issueDate,returnDate,fine
book_title,,,,,,
Computer Networks,219,Anjali MishraSachin Chauhan,MECSE,06/June/202618/June/2026,20/June/202602/July/2026,20
Data Structures,206,Aarav SharmaVikas Yadav,CSECivil,01/June/202608/June/2026,15/June/202622/June/2026,0
Database Systems,216,Anjali MishraPooja Sharma,CSECivil,09/June/202613/June/2026,23/June/202627/June/2026,40
Digital Electronics,103,Rohan Verma,ECE,05/June/2026,19/June/2026,0
Machine Learning,107,Ritika Jain,IT,10/June/2026,24/June/2026,0
Microprocessors,108,Simran Kaur,ECE,11/June/2026,25/June/2026,5
Operating Systems,337,Aditya KumarSimran KaurRitika Jain,CSEITME,14/June/202615/June/202617/June/2026,28/June/202629/June/202601/July/2026,40
Python Programming,102,Priya Singh,IT,03/June/2026,17/June/2026,10
Surveying Basics,113,Sachin Chauhan,ECE,16/June/2026,30/June/2026,0
Thermodynamics,109,Raj Malhotra,ME,12/June/2026,26/June/2026,0

In [16]:
result = df.groupby('rollno').agg({'fine' : ['mean', 'max', 'min']})
result

        fine
        mean max min
rollno
101      0.0   0   0
102     10.0  10  10
103      0.0   0   0
104     20.0  20  20
105      0.0   0   0
106     15.0  15  15
107      0.0   0   0
108      5.0   5   5
109      0.0   0   0
110     25.0  25  25
111      0.0   0   0
112     10.0  10  10
113      0.0   0   0
114     30.0  30  30
115      0.0   0   0

In [17]:
result = df.groupby('branch')['fine'].sum()
result

branch
CSE      15
Civil    25
ECE       5
IT       20
ME       50
Name: fine, dtype: int64

In [23]:
result = df.groupby('issueDate')['book_title'].count()
result

issueDate
01/June/2026    1
03/June/2026    1
05/June/2026    1
06/June/2026    1
08/June/2026    1
09/June/2026    1
10/June/2026    2
11/June/2026    1
13/June/2026    1
14/June/2026    1
15/June/2026    2
16/June/2026    1
18/June/2026    1
Name: book_title, dtype: int64

In [35]:
result = df.groupby(['rollno', 'name'])['issueDate'].count()
result

rollno  name
101     Aarav Sharma      1
102     Priya Singh       1
103     Rohan Verma       1
104     Anjali Mishra     1
105     Vikas Yadav       1
106     Anjali Mishra     1
107     Ritika Jain       1
108     Simran Kaur       1
109     Raj Malhotra      1
110     Pooja Sharma      1
111     Aditya Kumar      1
112     Simran Kaur       1
113     Sachin Chauhan    1
114     Ritika Jain       1
115     Sachin Chauhan    1
Name: issueDate, dtype: int64